//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardian
    {
        public int GuardianId { get; set; }
        public string GuardianFirstName { get; set; }
        public string GuardianLastName { get; set; }
        public string GuardianOtherName { get; set; }
        public string GuardianOccupation { get; set; }
        public string P_O_Box { get; set; }
        public int PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
    }
}
