//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighSchool
    {
        public int HighSchoolId { get; set; }
        public string NameOfSHS { get; set; }
        public string P_O_Box { get; set; }
        public string ClubAssociation { get; set; }
        public string PositionHeld { get; set; }
        public int IndexNumber { get; set; }
        public string ExamType { get; set; }
        public string RegionId { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ExamType ExamType1 { get; set; }
        public virtual Region Region { get; set; }
        public virtual Year Year1 { get; set; }
    }
}
