//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIn
    {
        public int SchoolId { get; set; }
        public string Serial { get; set; }
        public int Pin { get; set; }
    
        public virtual Serial Serial1 { get; set; }
        public virtual Serial Serial2 { get; set; }
    }
}
