//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdmissionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string OtherName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public byte[] Image { get; set; }
        public int PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Hometown { get; set; }
        public string P_O_Box { get; set; }
        public string HouseAddress { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        public virtual Nationality Nationality1 { get; set; }
        public virtual Religion Religion1 { get; set; }
    }
}
